/*
 * Albion Online Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.MarketStatResponsev2;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MarketStatChartResponsev2
 */


public class MarketStatChartResponsev2 {
  @SerializedName("location")
  private String location = null;

  @SerializedName("itemTypeId")
  private String itemTypeId = null;

  @SerializedName("qualityLevel")
  private Integer qualityLevel = null;

  @SerializedName("data")
  private MarketStatResponsev2 data = null;

  public MarketStatChartResponsev2 location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @Schema(description = "")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public MarketStatChartResponsev2 itemTypeId(String itemTypeId) {
    this.itemTypeId = itemTypeId;
    return this;
  }

   /**
   * Get itemTypeId
   * @return itemTypeId
  **/
  @Schema(description = "")
  public String getItemTypeId() {
    return itemTypeId;
  }

  public void setItemTypeId(String itemTypeId) {
    this.itemTypeId = itemTypeId;
  }

  public MarketStatChartResponsev2 qualityLevel(Integer qualityLevel) {
    this.qualityLevel = qualityLevel;
    return this;
  }

   /**
   * Get qualityLevel
   * @return qualityLevel
  **/
  @Schema(description = "")
  public Integer getQualityLevel() {
    return qualityLevel;
  }

  public void setQualityLevel(Integer qualityLevel) {
    this.qualityLevel = qualityLevel;
  }

  public MarketStatChartResponsev2 data(MarketStatResponsev2 data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public MarketStatResponsev2 getData() {
    return data;
  }

  public void setData(MarketStatResponsev2 data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketStatChartResponsev2 marketStatChartResponsev2 = (MarketStatChartResponsev2) o;
    return Objects.equals(this.location, marketStatChartResponsev2.location) &&
        Objects.equals(this.itemTypeId, marketStatChartResponsev2.itemTypeId) &&
        Objects.equals(this.qualityLevel, marketStatChartResponsev2.qualityLevel) &&
        Objects.equals(this.data, marketStatChartResponsev2.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(location, itemTypeId, qualityLevel, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketStatChartResponsev2 {\n");
    
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    itemTypeId: ").append(toIndentedString(itemTypeId)).append("\n");
    sb.append("    qualityLevel: ").append(toIndentedString(qualityLevel)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
