/*
 * Albion Online Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.MarketHistoryResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * MarketHistoriesResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-06T23:40:29.678+02:00[Europe/Berlin]")
public class MarketHistoriesResponse {
  @SerializedName("location")
  private String location = null;

  @SerializedName("itemTypeId")
  private String itemTypeId = null;

  @SerializedName("qualityLevel")
  private Integer qualityLevel = null;

  @SerializedName("data")
  private List<MarketHistoryResponse> data = null;

  public MarketHistoriesResponse location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @Schema(description = "")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public MarketHistoriesResponse itemTypeId(String itemTypeId) {
    this.itemTypeId = itemTypeId;
    return this;
  }

   /**
   * Get itemTypeId
   * @return itemTypeId
  **/
  @Schema(description = "")
  public String getItemTypeId() {
    return itemTypeId;
  }

  public void setItemTypeId(String itemTypeId) {
    this.itemTypeId = itemTypeId;
  }

  public MarketHistoriesResponse qualityLevel(Integer qualityLevel) {
    this.qualityLevel = qualityLevel;
    return this;
  }

   /**
   * Get qualityLevel
   * @return qualityLevel
  **/
  @Schema(description = "")
  public Integer getQualityLevel() {
    return qualityLevel;
  }

  public void setQualityLevel(Integer qualityLevel) {
    this.qualityLevel = qualityLevel;
  }

  public MarketHistoriesResponse data(List<MarketHistoryResponse> data) {
    this.data = data;
    return this;
  }

  public MarketHistoriesResponse addDataItem(MarketHistoryResponse dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<MarketHistoryResponse>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public List<MarketHistoryResponse> getData() {
    return data;
  }

  public void setData(List<MarketHistoryResponse> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketHistoriesResponse marketHistoriesResponse = (MarketHistoriesResponse) o;
    return Objects.equals(this.location, marketHistoriesResponse.location) &&
        Objects.equals(this.itemTypeId, marketHistoriesResponse.itemTypeId) &&
        Objects.equals(this.qualityLevel, marketHistoriesResponse.qualityLevel) &&
        Objects.equals(this.data, marketHistoriesResponse.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(location, itemTypeId, qualityLevel, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketHistoriesResponse {\n");
    
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    itemTypeId: ").append(toIndentedString(itemTypeId)).append("\n");
    sb.append("    qualityLevel: ").append(toIndentedString(qualityLevel)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
