/*
 * Albion Online Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * MarketResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-06T23:40:29.678+02:00[Europe/Berlin]")
public class MarketResponse {
  @SerializedName("itemTypeId")
  private String itemTypeId = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("qualityLevel")
  private Integer qualityLevel = null;

  @SerializedName("sellPriceMin")
  private Long sellPriceMin = null;

  @SerializedName("sellPriceMinDate")
  private OffsetDateTime sellPriceMinDate = null;

  @SerializedName("sellPriceMax")
  private Long sellPriceMax = null;

  @SerializedName("sellPriceMaxDate")
  private OffsetDateTime sellPriceMaxDate = null;

  @SerializedName("buyPriceMin")
  private Long buyPriceMin = null;

  @SerializedName("buyPriceMinDate")
  private OffsetDateTime buyPriceMinDate = null;

  @SerializedName("buyPriceMax")
  private Long buyPriceMax = null;

  @SerializedName("buyPriceMaxDate")
  private OffsetDateTime buyPriceMaxDate = null;

  public MarketResponse itemTypeId(String itemTypeId) {
    this.itemTypeId = itemTypeId;
    return this;
  }

   /**
   * Get itemTypeId
   * @return itemTypeId
  **/
  @Schema(description = "")
  public String getItemTypeId() {
    return itemTypeId;
  }

  public void setItemTypeId(String itemTypeId) {
    this.itemTypeId = itemTypeId;
  }

  public MarketResponse city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @Schema(description = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public MarketResponse qualityLevel(Integer qualityLevel) {
    this.qualityLevel = qualityLevel;
    return this;
  }

   /**
   * Get qualityLevel
   * @return qualityLevel
  **/
  @Schema(description = "")
  public Integer getQualityLevel() {
    return qualityLevel;
  }

  public void setQualityLevel(Integer qualityLevel) {
    this.qualityLevel = qualityLevel;
  }

  public MarketResponse sellPriceMin(Long sellPriceMin) {
    this.sellPriceMin = sellPriceMin;
    return this;
  }

   /**
   * Get sellPriceMin
   * @return sellPriceMin
  **/
  @Schema(description = "")
  public Long getSellPriceMin() {
    return sellPriceMin;
  }

  public void setSellPriceMin(Long sellPriceMin) {
    this.sellPriceMin = sellPriceMin;
  }

  public MarketResponse sellPriceMinDate(OffsetDateTime sellPriceMinDate) {
    this.sellPriceMinDate = sellPriceMinDate;
    return this;
  }

   /**
   * Get sellPriceMinDate
   * @return sellPriceMinDate
  **/
  @Schema(description = "")
  public OffsetDateTime getSellPriceMinDate() {
    return sellPriceMinDate;
  }

  public void setSellPriceMinDate(OffsetDateTime sellPriceMinDate) {
    this.sellPriceMinDate = sellPriceMinDate;
  }

  public MarketResponse sellPriceMax(Long sellPriceMax) {
    this.sellPriceMax = sellPriceMax;
    return this;
  }

   /**
   * Get sellPriceMax
   * @return sellPriceMax
  **/
  @Schema(description = "")
  public Long getSellPriceMax() {
    return sellPriceMax;
  }

  public void setSellPriceMax(Long sellPriceMax) {
    this.sellPriceMax = sellPriceMax;
  }

  public MarketResponse sellPriceMaxDate(OffsetDateTime sellPriceMaxDate) {
    this.sellPriceMaxDate = sellPriceMaxDate;
    return this;
  }

   /**
   * Get sellPriceMaxDate
   * @return sellPriceMaxDate
  **/
  @Schema(description = "")
  public OffsetDateTime getSellPriceMaxDate() {
    return sellPriceMaxDate;
  }

  public void setSellPriceMaxDate(OffsetDateTime sellPriceMaxDate) {
    this.sellPriceMaxDate = sellPriceMaxDate;
  }

  public MarketResponse buyPriceMin(Long buyPriceMin) {
    this.buyPriceMin = buyPriceMin;
    return this;
  }

   /**
   * Get buyPriceMin
   * @return buyPriceMin
  **/
  @Schema(description = "")
  public Long getBuyPriceMin() {
    return buyPriceMin;
  }

  public void setBuyPriceMin(Long buyPriceMin) {
    this.buyPriceMin = buyPriceMin;
  }

  public MarketResponse buyPriceMinDate(OffsetDateTime buyPriceMinDate) {
    this.buyPriceMinDate = buyPriceMinDate;
    return this;
  }

   /**
   * Get buyPriceMinDate
   * @return buyPriceMinDate
  **/
  @Schema(description = "")
  public OffsetDateTime getBuyPriceMinDate() {
    return buyPriceMinDate;
  }

  public void setBuyPriceMinDate(OffsetDateTime buyPriceMinDate) {
    this.buyPriceMinDate = buyPriceMinDate;
  }

  public MarketResponse buyPriceMax(Long buyPriceMax) {
    this.buyPriceMax = buyPriceMax;
    return this;
  }

   /**
   * Get buyPriceMax
   * @return buyPriceMax
  **/
  @Schema(description = "")
  public Long getBuyPriceMax() {
    return buyPriceMax;
  }

  public void setBuyPriceMax(Long buyPriceMax) {
    this.buyPriceMax = buyPriceMax;
  }

  public MarketResponse buyPriceMaxDate(OffsetDateTime buyPriceMaxDate) {
    this.buyPriceMaxDate = buyPriceMaxDate;
    return this;
  }

   /**
   * Get buyPriceMaxDate
   * @return buyPriceMaxDate
  **/
  @Schema(description = "")
  public OffsetDateTime getBuyPriceMaxDate() {
    return buyPriceMaxDate;
  }

  public void setBuyPriceMaxDate(OffsetDateTime buyPriceMaxDate) {
    this.buyPriceMaxDate = buyPriceMaxDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketResponse marketResponse = (MarketResponse) o;
    return Objects.equals(this.itemTypeId, marketResponse.itemTypeId) &&
        Objects.equals(this.city, marketResponse.city) &&
        Objects.equals(this.qualityLevel, marketResponse.qualityLevel) &&
        Objects.equals(this.sellPriceMin, marketResponse.sellPriceMin) &&
        Objects.equals(this.sellPriceMinDate, marketResponse.sellPriceMinDate) &&
        Objects.equals(this.sellPriceMax, marketResponse.sellPriceMax) &&
        Objects.equals(this.sellPriceMaxDate, marketResponse.sellPriceMaxDate) &&
        Objects.equals(this.buyPriceMin, marketResponse.buyPriceMin) &&
        Objects.equals(this.buyPriceMinDate, marketResponse.buyPriceMinDate) &&
        Objects.equals(this.buyPriceMax, marketResponse.buyPriceMax) &&
        Objects.equals(this.buyPriceMaxDate, marketResponse.buyPriceMaxDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemTypeId, city, qualityLevel, sellPriceMin, sellPriceMinDate, sellPriceMax, sellPriceMaxDate, buyPriceMin, buyPriceMinDate, buyPriceMax, buyPriceMaxDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketResponse {\n");
    
    sb.append("    itemTypeId: ").append(toIndentedString(itemTypeId)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    qualityLevel: ").append(toIndentedString(qualityLevel)).append("\n");
    sb.append("    sellPriceMin: ").append(toIndentedString(sellPriceMin)).append("\n");
    sb.append("    sellPriceMinDate: ").append(toIndentedString(sellPriceMinDate)).append("\n");
    sb.append("    sellPriceMax: ").append(toIndentedString(sellPriceMax)).append("\n");
    sb.append("    sellPriceMaxDate: ").append(toIndentedString(sellPriceMaxDate)).append("\n");
    sb.append("    buyPriceMin: ").append(toIndentedString(buyPriceMin)).append("\n");
    sb.append("    buyPriceMinDate: ").append(toIndentedString(buyPriceMinDate)).append("\n");
    sb.append("    buyPriceMax: ").append(toIndentedString(buyPriceMax)).append("\n");
    sb.append("    buyPriceMaxDate: ").append(toIndentedString(buyPriceMaxDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
